services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - backend

  eureka-server:
    image: eurekaserver    # Make sure this matches your jib image name for eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - backend
    depends_on:
      - zipkin

  activity-service:
    image: activityservice   # Matches jib image name for activity-service
    container_name: activity-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=activity-service
      - SERVER_PORT=8082
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/fitnessdb
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - backend
    depends_on:
      - mongodb
      - eureka-server
      - zipkin

  ai-service:
    image: aiservice   # Matches jib image name for ai-service
    container_name: ai-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=ai-service
      - SERVER_PORT=8083
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/fitnessdb
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - backend
    depends_on:
      - mongodb
      - eureka-server
      - zipkin

  api-gateway:
    image: apiservice   # Matches jib image name for api-gateway
    container_name: api-gateway
    ports:
      - "8085:8085"
    environment:
      - SPRING_APPLICATION_NAME=API
      - SERVER_PORT=8085
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - SPRING_ZIPKIN_BASE_URL=http://zipkin:9411/
    networks:
      - backend
    depends_on:
      - eureka-server
      - zipkin
  eureka
networks:
  backend:
